# Generated by Django 2.1.7 on 2019-05-15 21:03

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190513_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='formatted_grammar',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='grammar',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
